import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

import dynamic from 'next/dynamic'
import ConvexClientProvider from '@/components/ConvexClientProvider'

const ClientClerkProvider = dynamic(() => import('@/components/ClientClerkProvider'), { ssr: false })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GetFeeds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overscroll-none`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClientClerkProvider>
            <ConvexClientProvider>
              {children}
            </ConvexClientProvider>
          </ClientClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

// End of file comment for Vercel redeploy